language: python

python:
  - "3.8"

# Only build if pushing to master or on pull requests without /no-ci/ specified
if: (type = push AND branch = master) OR (type = pull_request AND NOT branch =~ /no-ci/)

# Environment variables
env:
  - ROUGE_HOME=/home/travis/virtualenv/python3.8.7/lib/python3.8/site-packages/summ_eval/ROUGE-1.5.5/

# mpi4py installation apt-get setup
before_install:
  - sudo apt-get update
  - sudo apt-get install libopenmpi-dev

# Install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - python download.py

# Scripts: tests
script:
  - python tests/model_test.py
  - python tests/dataset_test.py
  - python tests/evaluation_test.py
