language: python

python:
  - "3.8"

# Install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py develop
  - python download.py

# Scripts: tests
script:
  - python tests/model_test.py
  - python tests/dataset_test.py
  - python tests/evaluation_test.py
