include = '\.pyi?$'

exclude = '''
(
      __pycache__
    | \.git
    | \.vscode
    | \.venv
)
'''

[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython"
]
build-backend = "setuptools.build_meta"